apiVersion: v2
name: external-dns
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "0.0.0"

dependencies:
  - name: external-dns
    repository: https://charts.bitnami.com/bitnami
    version: 8.8.2
