apiVersion: v2
name: dragonfly
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "0.0.0"

dependencies:
  - name: dragonfly
    repository: oci://ghcr.io/dragonflydb/dragonfly/helm
    version: v1.29.0