apiVersion: v2
name: reloader
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "0.0.0"

dependencies:
  - name: reloader
    repository: https://stakater.github.io/stakater-charts
    version: 2.2.3
